# Setup
title:        Vision5A
tagline:      Computer Vision Lecture
#logo:         images/

theme: jekyll-theme-hacker

# About/contact
author:
  name:       Aurelien Plyer
#  url:        TODO
include:
- _pages
